import type {
  Protocol,
  Chain,
  RiskLevel,
  ChartData,
  DistributionData,
  YieldOpportunity,
  GovernanceProposal,
} from "./types"

export const PROTOCOL_CATEGORIES = [
  "All",
  "Lending",
  "DEX",
  "Yield",
  "Derivatives",
  "Insurance",
  "Assets",
  "Payments",
  "Bridge",
]

export const RISK_LEVELS: Record<string, RiskLevel> = {
  low: { color: "bg-green-500", label: "Low Risk" },
  medium: { color: "bg-yellow-500", label: "Medium Risk" },
  high: { color: "bg-red-500", label: "High Risk" },
}

export const CHAINS: Chain[] = [
  { id: "ethereum", name: "Ethereum", icon: "/ethereum-logo.png" },
  { id: "polygon", name: "Polygon", icon: "/polygon-logo.png" },
  { id: "avalanche", name: "Avalanche", icon: "/avalanche-logo-abstract.png" },
  { id: "solana", name: "Solana", icon: "/solana-logo.png" },
  { id: "base", name: "Base", icon: "/base-chain-logo.png" },
]

export const PROTOCOLS: Protocol[] = [
  {
    id: "aave",
    name: "Aave",
    category: "Lending",
    icon: "/aave-logo.png",
    tvl: 5240000000,
    tvlChange: 2.3,
    apy: 3.8,
    risk: "low",
    chains: ["ethereum", "polygon", "avalanche"],
    description: "Decentralized lending protocol where users can lend and borrow crypto assets",
    audited: true,
    governance: true,
    favorite: true,
  },
  {
    id: "uniswap",
    name: "Uniswap",
    category: "DEX",
    icon: "/uniswap-logo.png",
    tvl: 3780000000,
    tvlChange: -1.2,
    apy: 4.2,
    risk: "low",
    chains: ["ethereum", "polygon", "base", "avalanche"],
    description: "Decentralized exchange protocol using automated market makers",
    audited: true,
    governance: true,
    favorite: false,
  },
  {
    id: "chainlink",
    name: "Chainlink",
    category: "Oracle",
    icon: "/chainlink-logo.png",
    tvl: 1890000000,
    tvlChange: 0.8,
    apy: 0,
    risk: "low",
    chains: ["ethereum", "polygon", "avalanche", "solana"],
    description: "Decentralized oracle network providing reliable data feeds to smart contracts",
    audited: true,
    governance: false,
    favorite: true,
  },
  {
    id: "compound",
    name: "Compound",
    category: "Lending",
    icon: "/placeholder-v65ug.png",
    tvl: 1450000000,
    tvlChange: -0.5,
    apy: 3.2,
    risk: "medium",
    chains: ["ethereum", "base"],
    description: "Algorithmic money market protocol allowing users to lend and borrow assets",
    audited: true,
    governance: true,
    favorite: false,
  },
  {
    id: "curve",
    name: "Curve Finance",
    category: "DEX",
    icon: "/placeholder-h9j1l.png",
    tvl: 2980000000,
    tvlChange: 1.7,
    apy: 5.6,
    risk: "medium",
    chains: ["ethereum", "polygon", "avalanche"],
    description: "Decentralized exchange optimized for stablecoin trading with low slippage",
    audited: true,
    governance: true,
    favorite: false,
  },
  {
    id: "yearn",
    name: "Yearn Finance",
    category: "Yield",
    icon: "/placeholder-18a1i.png",
    tvl: 980000000,
    tvlChange: 3.2,
    apy: 8.4,
    risk: "medium",
    chains: ["ethereum", "polygon"],
    description: "Yield aggregator that automatically moves funds between DeFi lending protocols",
    audited: true,
    governance: true,
    favorite: false,
  },
  {
    id: "synthetix",
    name: "Synthetix",
    category: "Derivatives",
    icon: "/placeholder-j674c.png",
    tvl: 720000000,
    tvlChange: -2.1,
    apy: 7.8,
    risk: "high",
    chains: ["ethereum", "base"],
    description: "Derivatives liquidity protocol enabling the creation of synthetic assets",
    audited: true,
    governance: true,
    favorite: false,
  },
]

export const TVL_CHART_DATA: ChartData[] = [
  { name: "Jan", Aave: 4.8, Uniswap: 3.2, Curve: 2.5, Yearn: 0.8 },
  { name: "Feb", Aave: 4.9, Uniswap: 3.3, Curve: 2.6, Yearn: 0.9 },
  { name: "Mar", Aave: 5.0, Uniswap: 3.5, Curve: 2.7, Yearn: 0.9 },
  { name: "Apr", Aave: 5.1, Uniswap: 3.6, Curve: 2.8, Yearn: 1.0 },
  { name: "May", Aave: 5.0, Uniswap: 3.4, Curve: 2.9, Yearn: 0.9 },
  { name: "Jun", Aave: 5.2, Uniswap: 3.7, Curve: 3.0, Yearn: 1.0 },
  { name: "Jul", Aave: 5.3, Uniswap: 3.8, Curve: 3.0, Yearn: 1.0 },
]

export const PROTOCOL_DISTRIBUTION: DistributionData[] = [
  { name: "Lending", value: 42 },
  { name: "DEX", value: 28 },
  { name: "Yield", value: 15 },
  { name: "Derivatives", value: 10 },
  { name: "Other", value: 5 },
]

export const CHART_COLORS = ["#0088FE", "#00C49F", "#FFBB28", "#FF8042", "#8884D8"]

export const YIELD_OPPORTUNITIES: YieldOpportunity[] = [
  {
    protocol: "Aave",
    protocolIcon: "/aave-logo.png",
    asset: "USDC",
    assetIcon: "/usdc-logo.png",
    strategy: "Supply",
    apy: 4.2,
    risk: "low",
    chain: "Polygon",
    chainIcon: "/polygon-logo.png",
  },
  {
    protocol: "Curve",
    protocolIcon: "/placeholder-h9j1l.png",
    asset: "ETH/stETH",
    assetIcon: "/ethereum-logo.png",
    strategy: "Liquidity Pool",
    apy: 6.8,
    risk: "medium",
    chain: "Ethereum",
    chainIcon: "/ethereum-logo.png",
  },
  {
    protocol: "Yearn",
    protocolIcon: "/placeholder-18a1i.png",
    asset: "USDC",
    assetIcon: "/usdc-logo.png",
    strategy: "Vault",
    apy: 8.4,
    risk: "medium",
    chain: "Ethereum",
    chainIcon: "/ethereum-logo.png",
  },
  {
    protocol: "Uniswap",
    protocolIcon: "/uniswap-logo.png",
    asset: "ETH/USDC",
    assetIcon: "/ethereum-logo.png",
    strategy: "Concentrated Liquidity",
    apy: 7.2,
    risk: "medium",
    chain: "Base",
    chainIcon: "/base-chain-logo.png",
  },
]

export const GOVERNANCE_PROPOSALS: GovernanceProposal[] = [
  {
    id: "aip-123",
    protocol: "Aave",
    title: "AIP-123: Update Risk Parameters",
    description: "Proposal to update risk parameters for stablecoin markets",
    status: "active",
    endDate: "2 days",
    forPercentage: 76,
  },
  {
    id: "uip-45",
    protocol: "Uniswap",
    title: "UIP-45: Fee Structure Update",
    description: "Proposal to adjust fee tiers for low volatility pairs",
    status: "active",
    endDate: "5 days",
    forPercentage: 82,
  },
]
