import type { ArbitrageBot, Exchange, ArbitrageOpportunity } from "./types"

export const mockBots: ArbitrageBot[] = [
  {
    id: "1",
    name: "BTC/USDT Arbitrage",
    description: "High-frequency arbitrage bot for Bitcoin trading",
    status: "active",
    exchanges: ["binance", "coinbase"],
    pairs: ["BTC/USDT"],
    minSpread: 0.5,
    profitThreshold: 50,
    successRate: 94.5,
    totalProfit: 2547.82,
    totalTrades: 156,
    createdAt: new Date("2024-01-15"),
    strategy: "basic",
    riskLevel: "medium",
  },
  {
    id: "2",
    name: "ETH Multi-Exchange",
    description: "Ethereum arbitrage across multiple exchanges",
    status: "active",
    exchanges: ["binance", "kraken", "coinbase"],
    pairs: ["ETH/USDT", "ETH/BTC"],
    minSpread: 0.3,
    profitThreshold: 30,
    successRate: 91.2,
    totalProfit: 1876.45,
    totalTrades: 203,
    createdAt: new Date("2024-01-20"),
    strategy: "advanced",
    riskLevel: "low",
  },
  {
    id: "3",
    name: "Altcoin Hunter",
    description: "Opportunistic arbitrage for various altcoins",
    status: "paused",
    exchanges: ["binance", "kucoin"],
    pairs: ["ADA/USDT", "SOL/USDT", "MATIC/USDT"],
    minSpread: 1.0,
    profitThreshold: 100,
    successRate: 87.3,
    totalProfit: 945.23,
    totalTrades: 89,
    createdAt: new Date("2024-02-01"),
    strategy: "basic",
    riskLevel: "high",
  },
]

export const mockExchanges: Exchange[] = [
  {
    id: "binance",
    name: "Binance",
    logo: "/placeholder.svg",
    status: "connected",
    apiKeyConfigured: true,
    balance: 15420.50,
    tradingFees: 0.1,
  },
  {
    id: "coinbase",
    name: "Coinbase Pro",
    logo: "/placeholder.svg",
    status: "connected",
    apiKeyConfigured: true,
    balance: 8750.25,
    tradingFees: 0.15,
  },
  {
    id: "kraken",
    name: "Kraken",
    logo: "/placeholder.svg",
    status: "connected",
    apiKeyConfigured: true,
    balance: 6230.75,
    tradingFees: 0.16,
  },
  {
    id: "kucoin",
    name: "KuCoin",
    logo: "/placeholder.svg",
    status: "disconnected",
    apiKeyConfigured: false,
    balance: 0,
    tradingFees: 0.1,
  },
  {
    id: "huobi",
    name: "Huobi Global",
    logo: "/placeholder.svg",
    status: "error",
    apiKeyConfigured: true,
    balance: 3450.00,
    tradingFees: 0.2,
  },
]

export const mockOpportunities: ArbitrageOpportunity[] = [
  {
    id: "1",
    pair: "BTC/USDT",
    buyExchange: "Binance",
    sellExchange: "Coinbase",
    buyPrice: 43250.50,
    sellPrice: 43785.75,
    spread: 1.24,
    profit: 535.25,
    volume: 10000,
    timestamp: new Date(),
    status: "active",
    estimatedExecutionTime: 2.5,
    risk: "low",
  },
  {
    id: "2",
    pair: "ETH/USDT",
    buyExchange: "Kraken",
    sellExchange: "Binance",
    buyPrice: 2285.30,
    sellPrice: 2325.80,
    spread: 1.77,
    profit: 405.00,
    volume: 10000,
    timestamp: new Date(),
    status: "active",
    estimatedExecutionTime: 3.2,
    risk: "low",
  },
  {
    id: "3",
    pair: "SOL/USDT",
    buyExchange: "KuCoin",
    sellExchange: "Binance",
    buyPrice: 98.45,
    sellPrice: 101.20,
    spread: 2.79,
    profit: 275.00,
    volume: 10000,
    timestamp: new Date(),
    status: "active",
    estimatedExecutionTime: 4.1,
    risk: "medium",
  },
  {
    id: "4",
    pair: "ADA/USDT",
    buyExchange: "Binance",
    sellExchange: "Coinbase",
    buyPrice: 0.5124,
    sellPrice: 0.5287,
    spread: 3.18,
    profit: 163.00,
    volume: 10000,
    timestamp: new Date(),
    status: "active",
    estimatedExecutionTime: 3.8,
    risk: "high",
  },
]

export const mockStats = {
  totalProfit: 5369.50,
  successRate: 92.1,
  totalTrades: 448,
  activeOpportunities: 4,
  activeBots: 2,
  totalBots: 3,
  bestPair: "BTC/USDT",
  bestExchangePair: "Binance → Coinbase",
  largestSpread: 3.18,
  avgExecutionTime: 3.4,
}
