import type { Strategy, TimeFrame } from "./types"

// Helper function to generate chart data
const generateChartData = (timeFrame: TimeFrame, baseMultiplier = 1) => {
  const dataPoints = {
    "1D": 24,
    "1W": 7,
    "1M": 30,
    "3M": 12,
    "6M": 6,
    "1Y": 12,
    All: 24,
  }

  const count = dataPoints[timeFrame]
  const getLabel = (i: number) => {
    switch (timeFrame) {
      case "1D":
        return `${i}:00`
      case "1W":
        return `Day ${i + 1}`
      case "1M":
        return `Day ${i + 1}`
      case "3M":
      case "6M":
        return timeFrame === "3M" ? `Week ${i + 1}` : `Month ${i + 1}`
      case "1Y":
      case "All":
        return `Month ${i + 1}`
      default:
        return `${i + 1}`
    }
  }

  return Array(count)
    .fill(0)
    .map((_, i) => ({
      date: getLabel(i),
      value:
        1000 * (1 + Math.sin(i / (3 + baseMultiplier)) * (0.05 + baseMultiplier * 0.02) + i / (240 / baseMultiplier)),
    }))
}

export const mockStrategies: Strategy[] = [
  {
    id: "s1",
    name: "AI Alpha Predictor",
    description:
      "Advanced AI-powered strategy that predicts market movements using machine learning algorithms trained on historical data and real-time market conditions.",
    category: "AI-Powered",
    creator: {
      id: "c1",
      name: "CryptoAI Labs",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      strategies: 12,
      followers: 2450,
    },
    price: 299,
    subscription: {
      monthly: 29.99,
      yearly: 299.99,
    },
    isFree: false,
    rating: 4.8,
    reviews: 156,
    purchases: 1245,
    returns: {
      daily: 0.8,
      weekly: 5.2,
      monthly: 18.5,
      yearly: 215.4,
    },
    risk: "Medium",
    winRate: 68.5,
    profitFactor: 2.3,
    maxDrawdown: 15.2,
    timeInMarket: 65,
    tradesPerDay: 3.5,
    supportedExchanges: ["Binance", "Coinbase", "Kraken", "Bybit"],
    supportedPairs: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "XRP/USDT"],
    tags: ["AI", "Machine Learning", "Multi-pair", "Spot Trading"],
    lastUpdated: "2023-04-15",
    chartData: {
      "1D": generateChartData("1D", 1),
      "1W": generateChartData("1W", 1),
      "1M": generateChartData("1M", 1),
      "3M": generateChartData("3M", 1),
      "6M": generateChartData("6M", 1),
      "1Y": generateChartData("1Y", 1),
      All: generateChartData("All", 1),
    },
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isFavorite: true,
    isPurchased: false,
  },
  {
    id: "s2",
    name: "Quantum Trend Surfer",
    description:
      "Sophisticated trend-following strategy that identifies and rides strong market trends while implementing smart exit strategies to maximize profits.",
    category: "Trend Following",
    creator: {
      id: "c2",
      name: "QuantEdge",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      strategies: 8,
      followers: 1850,
    },
    price: 199,
    isFree: false,
    rating: 4.6,
    reviews: 98,
    purchases: 876,
    returns: {
      daily: 0.6,
      weekly: 4.1,
      monthly: 16.2,
      yearly: 189.5,
    },
    risk: "Medium",
    winRate: 62.3,
    profitFactor: 2.1,
    maxDrawdown: 18.7,
    timeInMarket: 58,
    tradesPerDay: 2.8,
    supportedExchanges: ["Binance", "Bybit", "KuCoin"],
    supportedPairs: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "AVAX/USDT"],
    tags: ["Trend Following", "Technical Analysis", "Multi-timeframe"],
    lastUpdated: "2023-03-28",
    chartData: {
      "1D": generateChartData("1D", 1.2),
      "1W": generateChartData("1W", 1.2),
      "1M": generateChartData("1M", 1.2),
      "3M": generateChartData("3M", 1.2),
      "6M": generateChartData("6M", 1.2),
      "1Y": generateChartData("1Y", 1.2),
      All: generateChartData("All", 1.2),
    },
    isFeatured: false,
    isNew: false,
    isTrending: true,
    isFavorite: false,
    isPurchased: false,
  },
  {
    id: "s3",
    name: "Reversal Hunter Pro",
    description:
      "Mean reversion strategy that identifies overbought and oversold conditions to capture price reversals with high probability setups.",
    category: "Mean Reversion",
    creator: {
      id: "c3",
      name: "TradingAlpha",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: false,
      strategies: 5,
      followers: 920,
    },
    price: 149,
    isFree: false,
    rating: 4.5,
    reviews: 72,
    purchases: 645,
    returns: {
      daily: 0.7,
      weekly: 4.8,
      monthly: 15.6,
      yearly: 172.8,
    },
    risk: "Medium",
    winRate: 71.2,
    profitFactor: 1.9,
    maxDrawdown: 14.5,
    timeInMarket: 42,
    tradesPerDay: 4.2,
    supportedExchanges: ["Binance", "Bybit", "OKX"],
    supportedPairs: ["BTC/USDT", "ETH/USDT", "ADA/USDT", "DOT/USDT"],
    tags: ["Mean Reversion", "Oscillators", "Volatility"],
    lastUpdated: "2023-04-02",
    chartData: {
      "1D": generateChartData("1D", 0.8),
      "1W": generateChartData("1W", 0.8),
      "1M": generateChartData("1M", 0.8),
      "3M": generateChartData("3M", 0.8),
      "6M": generateChartData("6M", 0.8),
      "1Y": generateChartData("1Y", 0.8),
      All: generateChartData("All", 0.8),
    },
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isFavorite: false,
    isPurchased: false,
  },
  {
    id: "s4",
    name: "Breakout Momentum",
    description:
      "Captures explosive price movements by identifying key breakout levels and entering with momentum confirmation for maximum profit potential.",
    category: "Breakout",
    creator: {
      id: "c4",
      name: "MomentumTraders",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      strategies: 7,
      followers: 1560,
    },
    price: 179,
    isFree: false,
    rating: 4.7,
    reviews: 89,
    purchases: 732,
    returns: {
      daily: 0.9,
      weekly: 5.6,
      monthly: 19.2,
      yearly: 198.7,
    },
    risk: "High",
    winRate: 58.4,
    profitFactor: 2.4,
    maxDrawdown: 22.3,
    timeInMarket: 35,
    tradesPerDay: 2.1,
    supportedExchanges: ["Binance", "Bybit", "FTX"],
    supportedPairs: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "AVAX/USDT", "MATIC/USDT"],
    tags: ["Breakout", "Volume Analysis", "Momentum"],
    lastUpdated: "2023-04-10",
    chartData: {
      "1D": generateChartData("1D", 1.5),
      "1W": generateChartData("1W", 1.5),
      "1M": generateChartData("1M", 1.5),
      "3M": generateChartData("3M", 1.5),
      "6M": generateChartData("6M", 1.5),
      "1Y": generateChartData("1Y", 1.5),
      All: generateChartData("All", 1.5),
    },
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isFavorite: false,
    isPurchased: false,
  },
  {
    id: "s5",
    name: "Scalping Master",
    description:
      "High-frequency trading strategy designed for quick in-and-out trades to capture small price movements with high win rate and low risk per trade.",
    category: "Scalping",
    creator: {
      id: "c5",
      name: "ScalpKing",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      strategies: 4,
      followers: 2100,
    },
    price: 249,
    isFree: false,
    rating: 4.9,
    reviews: 134,
    purchases: 1120,
    returns: {
      daily: 1.2,
      weekly: 6.8,
      monthly: 22.5,
      yearly: 245.6,
    },
    risk: "Medium",
    winRate: 76.8,
    profitFactor: 1.8,
    maxDrawdown: 12.1,
    timeInMarket: 28,
    tradesPerDay: 15.3,
    supportedExchanges: ["Binance", "Bybit"],
    supportedPairs: ["BTC/USDT", "ETH/USDT"],
    tags: ["Scalping", "High-Frequency", "Low Timeframe"],
    lastUpdated: "2023-04-18",
    chartData: {
      "1D": generateChartData("1D", 2),
      "1W": generateChartData("1W", 2),
      "1M": generateChartData("1M", 2),
      "3M": generateChartData("3M", 2),
      "6M": generateChartData("6M", 2),
      "1Y": generateChartData("1Y", 2),
      All: generateChartData("All", 2),
    },
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isFavorite: true,
    isPurchased: false,
  },
  {
    id: "s6",
    name: "Grid Trading Pro",
    description:
      "Automated grid trading strategy that places buy and sell orders at regular price intervals to profit from market volatility in sideways markets.",
    category: "Grid Trading",
    creator: {
      id: "c6",
      name: "GridMaster",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: false,
      strategies: 3,
      followers: 780,
    },
    price: 129,
    isFree: false,
    rating: 4.4,
    reviews: 56,
    purchases: 420,
    returns: {
      daily: 0.5,
      weekly: 3.4,
      monthly: 12.8,
      yearly: 142.5,
    },
    risk: "Low",
    winRate: 82.3,
    profitFactor: 1.6,
    maxDrawdown: 8.7,
    timeInMarket: 95,
    tradesPerDay: 8.5,
    supportedExchanges: ["Binance", "KuCoin"],
    supportedPairs: ["BTC/USDT", "ETH/USDT", "BNB/USDT"],
    tags: ["Grid Trading", "Range-Bound", "Automated"],
    lastUpdated: "2023-03-25",
    chartData: {
      "1D": generateChartData("1D", 0.5),
      "1W": generateChartData("1W", 0.5),
      "1M": generateChartData("1M", 0.5),
      "3M": generateChartData("3M", 0.5),
      "6M": generateChartData("6M", 0.5),
      "1Y": generateChartData("1Y", 0.5),
      All: generateChartData("All", 0.5),
    },
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isFavorite: false,
    isPurchased: false,
  },
  {
    id: "s7",
    name: "Smart DCA Plus",
    description:
      "Enhanced dollar-cost averaging strategy that intelligently adjusts purchase amounts based on market conditions and technical indicators.",
    category: "DCA",
    creator: {
      id: "c7",
      name: "DCAWizard",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      strategies: 2,
      followers: 1350,
    },
    price: 0,
    isFree: true,
    rating: 4.3,
    reviews: 210,
    purchases: 3450,
    returns: {
      daily: 0.3,
      weekly: 2.1,
      monthly: 8.5,
      yearly: 95.6,
    },
    risk: "Low",
    winRate: 65.2,
    profitFactor: 1.5,
    maxDrawdown: 12.8,
    timeInMarket: 100,
    tradesPerDay: 0.5,
    supportedExchanges: ["Binance", "Coinbase", "Kraken", "KuCoin", "Bybit"],
    supportedPairs: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "ADA/USDT", "DOT/USDT", "AVAX/USDT"],
    tags: ["DCA", "Long-Term", "Beginner-Friendly", "Free"],
    lastUpdated: "2023-04-05",
    chartData: {
      "1D": generateChartData("1D", 0.3),
      "1W": generateChartData("1W", 0.3),
      "1M": generateChartData("1M", 0.3),
      "3M": generateChartData("3M", 0.3),
      "6M": generateChartData("6M", 0.3),
      "1Y": generateChartData("1Y", 0.3),
      All: generateChartData("All", 0.3),
    },
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isFavorite: false,
    isPurchased: true,
  },
  {
    id: "s8",
    name: "Cross-Exchange Arbitrage",
    description:
      "Exploits price differences between exchanges by simultaneously buying and selling the same asset to capture risk-free profits.",
    category: "Arbitrage",
    creator: {
      id: "c8",
      name: "ArbitrageNinja",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      strategies: 6,
      followers: 1980,
    },
    price: 349,
    subscription: {
      monthly: 34.99,
      yearly: 349.99,
    },
    isFree: false,
    rating: 4.7,
    reviews: 87,
    purchases: 560,
    returns: {
      daily: 0.6,
      weekly: 4.2,
      monthly: 16.8,
      yearly: 187.2,
    },
    risk: "Low",
    winRate: 92.5,
    profitFactor: 3.2,
    maxDrawdown: 5.3,
    timeInMarket: 15,
    tradesPerDay: 12.7,
    supportedExchanges: ["Binance", "Coinbase", "Kraken", "KuCoin", "Bybit", "OKX"],
    supportedPairs: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "XRP/USDT"],
    tags: ["Arbitrage", "Multi-Exchange", "Low Risk"],
    lastUpdated: "2023-04-12",
    chartData: {
      "1D": generateChartData("1D", 0.6),
      "1W": generateChartData("1W", 0.6),
      "1M": generateChartData("1M", 0.6),
      "3M": generateChartData("3M", 0.6),
      "6M": generateChartData("6M", 0.6),
      "1Y": generateChartData("1Y", 0.6),
      All: generateChartData("All", 0.6),
    },
    isFeatured: true,
    isNew: false,
    isTrending: false,
    isFavorite: false,
    isPurchased: false,
  },
]
