import type { BotTemplate } from "./types"

export const mockTemplates: BotTemplate[] = [
  {
    id: "1",
    name: "AI Trend Follower Pro",
    description: "Advanced AI-powered trend following bot that uses machine learning to identify and capitalize on market trends",
    price: 149,
    image: "/placeholder.svg",
    category: "AI",
    level: "Intermediate",
    isFeatured: true,
    isNew: false,
    isFavorite: false,
    isPurchased: false,
    winRate: 68,
    profitFactor: 2.4,
    maxDrawdown: 12,
    avgProfit: 3.2,
    creator: {
      name: "TradingAI Labs",
      verified: true,
    },
    rating: 4.8,
    reviewCount: 342,
  },
  {
    id: "2",
    name: "Smart DeFi Yield Optimizer",
    description: "Automated yield farming bot that optimizes returns across DeFi protocols with intelligent rebalancing",
    price: 299,
    image: "/placeholder.svg",
    category: "DeFi",
    level: "Advanced",
    isFeatured: true,
    isNew: false,
    isFavorite: true,
    isPurchased: false,
    winRate: 88,
    profitFactor: 3.5,
    maxDrawdown: 10,
    avgProfit: 5.2,
    creator: {
      name: "DeFiWhiz",
      verified: true,
    },
    rating: 4.9,
    reviewCount: 201,
  },
  {
    id: "3",
    name: "DCA Master",
    description: "Automated Dollar-Cost Averaging bot with smart timing features to optimize entry points",
    price: 79,
    image: "/placeholder.svg",
    category: "DCA",
    level: "Beginner",
    isFeatured: true,
    isNew: false,
    isFavorite: false,
    isPurchased: true,
    winRate: 72,
    profitFactor: 1.9,
    maxDrawdown: 8,
    avgProfit: 2.1,
    creator: {
      name: "CryptoStack",
      verified: true,
    },
    rating: 4.6,
    reviewCount: 215,
  },
  {
    id: "4",
    name: "Sentiment Trader AI",
    description: "AI-powered bot that analyzes social media, news, and market sentiment to make informed trading decisions",
    price: 199,
    image: "/placeholder.svg",
    category: "AI",
    level: "Advanced",
    isFeatured: false,
    isNew: true,
    isFavorite: false,
    isPurchased: false,
    winRate: 71,
    profitFactor: 2.2,
    maxDrawdown: 16,
    avgProfit: 3.8,
    creator: {
      name: "SentimentAI",
      verified: true,
    },
    rating: 4.7,
    reviewCount: 165,
  },
  {
    id: "5",
    name: "Grid Trading Pro",
    description: "Professional grid trading bot with customizable parameters for range-bound markets",
    price: 129,
    image: "/placeholder.svg",
    category: "Grid",
    level: "Intermediate",
    isFeatured: false,
    isNew: false,
    isFavorite: false,
    isPurchased: false,
    winRate: 65,
    profitFactor: 1.8,
    maxDrawdown: 14,
    avgProfit: 2.5,
    creator: {
      name: "GridMaster",
      verified: false,
    },
    rating: 4.4,
    reviewCount: 189,
  },
  {
    id: "6",
    name: "Flash Scalper",
    description: "High-frequency scalping bot optimized for capturing small price movements with minimal risk",
    price: 249,
    image: "/placeholder.svg",
    category: "Scalping",
    level: "Advanced",
    isFeatured: false,
    isNew: true,
    isFavorite: true,
    isPurchased: false,
    winRate: 74,
    profitFactor: 2.1,
    maxDrawdown: 18,
    avgProfit: 1.8,
    creator: {
      name: "ScalpingPro",
      verified: true,
    },
    rating: 4.5,
    reviewCount: 128,
  },
]
