import type { BotTemplate } from "./types";

export const botTemplatesData: BotTemplate[] = [
  {
    id: "bt-001",
    name: "AI Trend Follower Pro",
    description: "Advanced AI-powered trend following bot that uses machine learning to identify and follow market trends across multiple timeframes.",
    category: "AI",
    type: "Trend Following",
    complexity: "Intermediate",
    rating: 4.8,
    reviews: 342,
    creator: {
      name: "TradingAI Labs",
      avatar: "/trading-ai-labs.png",
      verified: true,
    },
    price: 149,
    features: ["Multi-timeframe analysis", "Adaptive entry/exit points", "Risk management system", "Real-time market analysis", "Customizable parameters"],
    exchanges: ["Binance", "Coinbase", "Kraken"],
    assets: ["BTC", "ETH", "SOL", "BNB", "ADA"],
    performance: {
      winRate: 68,
      profitFactor: 2.4,
      maxDrawdown: 12,
      averageProfit: 3.2,
    },
    popularity: 9870,
    lastUpdated: "2023-04-15",
    image: "/ai-trend-follower.png",
    isFeatured: true,
    isNew: false,
    isFavorite: true,
  },
  {
    id: "bt-002",
    name: "DCA Master",
    description: "Automated Dollar-Cost Averaging bot with smart timing features to optimize entry points based on market conditions.",
    category: "DCA",
    type: "Accumulation",
    complexity: "Beginner",
    rating: 4.6,
    reviews: 215,
    creator: {
      name: "CryptoStack",
      avatar: "/trading-ai-labs.png",
      verified: true,
    },
    price: 79,
    features: ["Smart timing algorithm", "Multiple asset support", "Customizable intervals", "Performance tracking", "Auto-rebalancing"],
    exchanges: ["Binance", "Coinbase", "FTX"],
    assets: ["BTC", "ETH", "DOT", "LINK", "AVAX"],
    performance: {
      winRate: 72,
      profitFactor: 1.9,
      maxDrawdown: 8,
      averageProfit: 2.1,
    },
    popularity: 7650,
    lastUpdated: "2023-05-22",
    image: "/dca-master.png",
    isFeatured: true,
    isNew: false,
    isFavorite: false,
  },
  {
    id: "bt-003",
    name: "Grid Trading Elite",
    description: "Advanced grid trading bot that automatically places buy and sell orders at predetermined intervals to profit from market volatility.",
    category: "Grid",
    type: "Market Making",
    complexity: "Advanced",
    rating: 4.7,
    reviews: 189,
    creator: {
      name: "AlgoTraders",
      avatar: "/algo-traders.png",
      verified: true,
    },
    price: 199,
    features: ["Dynamic grid spacing", "Auto grid adjustment", "Profit reinvestment", "Risk management", "Multi-pair support"],
    exchanges: ["Binance", "Kucoin", "Bybit"],
    assets: ["BTC", "ETH", "SOL", "AVAX", "MATIC"],
    performance: {
      winRate: 81,
      profitFactor: 2.8,
      maxDrawdown: 15,
      averageProfit: 4.5,
    },
    popularity: 6320,
    lastUpdated: "2023-06-10",
    image: "/grid-trading-elite.png",
    isFeatured: false,
    isNew: false,
    isFavorite: true,
  },
  {
    id: "bt-004",
    name: "Arbitrage Hunter",
    description: "Multi-exchange arbitrage bot that identifies and exploits price differences across exchanges with automated execution.",
    category: "Arbitrage",
    type: "Cross-Exchange",
    complexity: "Advanced",
    rating: 4.5,
    reviews: 156,
    creator: {
      name: "ArbitrageAI",
      avatar: "/dca-master.png",
      verified: true,
    },
    price: 249,
    features: ["Real-time price monitoring", "Fee optimization", "Slippage protection", "Multi-exchange support", "Automated execution"],
    exchanges: ["Binance", "Coinbase", "Kraken", "Kucoin", "Huobi"],
    assets: ["BTC", "ETH", "USDT", "USDC", "BNB"],
    performance: {
      winRate: 92,
      profitFactor: 3.2,
      maxDrawdown: 5,
      averageProfit: 1.8,
    },
    popularity: 5890,
    lastUpdated: "2023-07-05",
    image: "/arbitrage-hunter.png",
    isFeatured: false,
    isNew: true,
    isFavorite: false,
  },
  {
    id: "bt-005",
    name: "Momentum Scalper",
    description: "High-frequency trading bot that capitalizes on short-term momentum in crypto markets with precise entry and exit strategies.",
    category: "Scalping",
    type: "Momentum",
    complexity: "Intermediate",
    rating: 4.4,
    reviews: 132,
    creator: {
      name: "ScalperElite",
      avatar: "/defi-yield-optimizer.png",
      verified: false,
    },
    price: 129,
    features: ["High-frequency trading", "Momentum indicators", "Quick profit taking", "Stop-loss automation", "Performance analytics"],
    exchanges: ["Binance", "Bybit", "FTX"],
    assets: ["BTC", "ETH", "SOL", "AVAX", "MATIC"],
    performance: {
      winRate: 65,
      profitFactor: 1.7,
      maxDrawdown: 18,
      averageProfit: 2.9,
    },
    popularity: 4750,
    lastUpdated: "2023-08-12",
    image: "/momentum-scalper.png",
    isFeatured: false,
    isNew: false,
    isFavorite: false,
  },
  {
    id: "bt-006",
    name: "Smart DeFi Yield Optimizer",
    description: "Automated yield farming bot that optimizes returns across DeFi protocols with intelligent capital allocation and risk management.",
    category: "DeFi",
    type: "Yield Farming",
    complexity: "Advanced",
    rating: 4.9,
    reviews: 201,
    creator: {
      name: "DeFiWhiz",
      avatar: "/defi-yield-optimizer.png",
      verified: true,
    },
    price: 299,
    features: ["Multi-protocol optimization", "Gas fee optimization", "Impermanent loss protection", "Auto-compounding", "Risk diversification"],
    exchanges: ["Uniswap", "Curve", "Aave", "Compound", "Balancer"],
    assets: ["ETH", "USDC", "DAI", "AAVE", "CRV"],
    performance: {
      winRate: 88,
      profitFactor: 3.5,
      maxDrawdown: 10,
      averageProfit: 5.2,
    },
    popularity: 8920,
    lastUpdated: "2023-09-01",
    image: "/defi-yield-optimizer.png",
    isFeatured: true,
    isNew: false,
    isFavorite: true,
  },
  {
    id: "bt-007",
    name: "Breakout Trader",
    description: "Technical analysis bot that identifies and trades breakout patterns with confirmation filters and smart position sizing.",
    category: "Technical",
    type: "Breakout",
    complexity: "Intermediate",
    rating: 4.3,
    reviews: 118,
    creator: {
      name: "ChartMaster",
      avatar: "/sentiment-trader-ai.png",
      verified: false,
    },
    price: 99,
    features: ["Pattern recognition", "Volume confirmation", "Multiple timeframes", "Position sizing", "Trailing stop-loss"],
    exchanges: ["Binance", "Kucoin", "Bybit"],
    assets: ["BTC", "ETH", "SOL", "AVAX", "DOT"],
    performance: {
      winRate: 62,
      profitFactor: 1.8,
      maxDrawdown: 22,
      averageProfit: 4.1,
    },
    popularity: 3980,
    lastUpdated: "2023-10-18",
    image: "/breakout-trader.png",
    isFeatured: false,
    isNew: true,
    isFavorite: false,
  },
  {
    id: "bt-008",
    name: "Sentiment Trader AI",
    description: "AI-powered bot that analyzes social media, news, and market sentiment to make trading decisions with natural language processing.",
    category: "AI",
    type: "Sentiment Analysis",
    complexity: "Advanced",
    rating: 4.7,
    reviews: 165,
    creator: {
      name: "SentimentAI",
      avatar: "/algo-traders.png",
      verified: true,
    },
    price: 199,
    features: ["Social media analysis", "News sentiment scoring", "Market correlation", "Trend prediction", "Risk management"],
    exchanges: ["Binance", "Coinbase", "Kraken"],
    assets: ["BTC", "ETH", "SOL", "DOGE", "SHIB"],
    performance: {
      winRate: 71,
      profitFactor: 2.2,
      maxDrawdown: 16,
      averageProfit: 3.8,
    },
    popularity: 7120,
    lastUpdated: "2023-11-05",
    image: "/sentiment-trader-ai.png",
    isFeatured: true,
    isNew: true,
    isFavorite: false,
  },
];
