import { Landmark, Shield, Droplets, Layers } from "lucide-react"
import type { StakingPool, ActiveStake, HistoricalData, PortfolioAllocation } from "./types"

export const stakingPools: StakingPool[] = [
  {
    id: "eth-consensus",
    name: "Ethereum Consensus Layer",
    protocol: "Ethereum",
    token: "Ethereum",
    tokenSymbol: "ETH",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 4.2,
    tvl: 28500000000,
    lockPeriod: null,
    lockPeriodText: "No lock",
    minStake: 32,
    rewards: ["Staking Rewards"],
    rewardTokens: ["ETH"],
    rewardLogos: ["/placeholder.svg?height=32&width=32"],
    riskLevel: "Low",
    isLiquidStaking: false,
    isVerified: true,
    chain: "Ethereum",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: true,
    description: "Stake ETH directly with the Ethereum network to secure the blockchain and earn rewards.",
    stakingType: "PoS",
    stakingTypeLabel: "Proof of Stake",
    stakingTypeIcon: Landmark,
  },
  {
    id: "lido-eth",
    name: "Lido Liquid Staking",
    protocol: "Lido",
    token: "Ethereum",
    tokenSymbol: "ETH",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 3.8,
    tvl: 21300000000,
    lockPeriod: null,
    lockPeriodText: "No lock",
    minStake: 0.01,
    rewards: ["Staking Rewards", "LDO Rewards"],
    rewardTokens: ["stETH", "LDO"],
    rewardLogos: ["/placeholder.svg?height=32&width=32", "/placeholder.svg?height=32&width=32"],
    riskLevel: "Low",
    isLiquidStaking: true,
    isVerified: true,
    chain: "Ethereum",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: false,
    description:
      "Stake ETH and receive stETH while maintaining liquidity. Earn staking rewards without locking your assets.",
    stakingType: "Liquid",
    stakingTypeLabel: "Liquid Staking",
    stakingTypeIcon: Droplets,
  },
  {
    id: "rocket-pool",
    name: "Rocket Pool",
    protocol: "Rocket Pool",
    token: "Ethereum",
    tokenSymbol: "ETH",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 4.1,
    tvl: 2800000000,
    lockPeriod: null,
    lockPeriodText: "No lock",
    minStake: 0.01,
    rewards: ["Staking Rewards", "RPL Rewards"],
    rewardTokens: ["rETH", "RPL"],
    rewardLogos: ["/placeholder.svg?height=32&width=32", "/placeholder.svg?height=32&width=32"],
    riskLevel: "Low",
    isLiquidStaking: true,
    isVerified: true,
    chain: "Ethereum",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: false,
    description: "Decentralized ETH staking protocol offering rETH as a liquid staking token with competitive APY.",
    stakingType: "Liquid",
    stakingTypeLabel: "Liquid Staking",
    stakingTypeIcon: Droplets,
  },
  {
    id: "binance-bnb",
    name: "BNB Staking",
    protocol: "Binance",
    token: "BNB",
    tokenSymbol: "BNB",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 6.5,
    tvl: 3200000000,
    lockPeriod: 30,
    lockPeriodText: "30 days",
    minStake: 0.1,
    rewards: ["Staking Rewards"],
    rewardTokens: ["BNB"],
    rewardLogos: ["/placeholder.svg?height=32&width=32"],
    riskLevel: "Medium",
    isLiquidStaking: false,
    isVerified: true,
    chain: "BNB Chain",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: true,
    description: "Stake BNB to earn rewards while supporting the BNB Chain network security.",
    stakingType: "DPoS",
    stakingTypeLabel: "Delegated Proof of Stake",
    stakingTypeIcon: Shield,
  },
  {
    id: "solana-staking",
    name: "Solana Staking",
    protocol: "Solana",
    token: "Solana",
    tokenSymbol: "SOL",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 7.8,
    tvl: 4100000000,
    lockPeriod: null,
    lockPeriodText: "No lock",
    minStake: 1,
    rewards: ["Staking Rewards"],
    rewardTokens: ["SOL"],
    rewardLogos: ["/placeholder.svg?height=32&width=32"],
    riskLevel: "Medium",
    isLiquidStaking: false,
    isVerified: true,
    chain: "Solana",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: false,
    description: "Stake SOL with validators to secure the Solana network and earn staking rewards.",
    stakingType: "PoS",
    stakingTypeLabel: "Proof of Stake",
    stakingTypeIcon: Landmark,
  },
  {
    id: "marinade-sol",
    name: "Marinade Finance",
    protocol: "Marinade",
    token: "Solana",
    tokenSymbol: "SOL",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 6.9,
    tvl: 580000000,
    lockPeriod: null,
    lockPeriodText: "No lock",
    minStake: 0.01,
    rewards: ["Staking Rewards", "MNDE Rewards"],
    rewardTokens: ["mSOL", "MNDE"],
    rewardLogos: ["/placeholder.svg?height=32&width=32", "/placeholder.svg?height=32&width=32"],
    riskLevel: "Medium",
    isLiquidStaking: true,
    isVerified: true,
    chain: "Solana",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: false,
    description: "Liquid staking solution for Solana. Stake SOL and receive mSOL while maintaining liquidity.",
    stakingType: "Liquid",
    stakingTypeLabel: "Liquid Staking",
    stakingTypeIcon: Droplets,
  },
  {
    id: "polkadot-nomination",
    name: "Polkadot Nomination",
    protocol: "Polkadot",
    token: "Polkadot",
    tokenSymbol: "DOT",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 14.2,
    tvl: 1900000000,
    lockPeriod: 28,
    lockPeriodText: "28 days",
    minStake: 10,
    rewards: ["Staking Rewards"],
    rewardTokens: ["DOT"],
    rewardLogos: ["/placeholder.svg?height=32&width=32"],
    riskLevel: "Medium",
    isLiquidStaking: false,
    isVerified: true,
    chain: "Polkadot",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: false,
    description: "Nominate validators on Polkadot to earn staking rewards while securing the network.",
    stakingType: "DPoS",
    stakingTypeLabel: "Delegated Proof of Stake",
    stakingTypeIcon: Shield,
  },
  {
    id: "cardano-staking",
    name: "Cardano Staking",
    protocol: "Cardano",
    token: "Cardano",
    tokenSymbol: "ADA",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 5.2,
    tvl: 2700000000,
    lockPeriod: null,
    lockPeriodText: "No lock",
    minStake: 10,
    rewards: ["Staking Rewards"],
    rewardTokens: ["ADA"],
    rewardLogos: ["/placeholder.svg?height=32&width=32"],
    riskLevel: "Low",
    isLiquidStaking: false,
    isVerified: true,
    chain: "Cardano",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: false,
    description: "Delegate ADA to stake pools to earn rewards while supporting the Cardano network.",
    stakingType: "PoS",
    stakingTypeLabel: "Proof of Stake",
    stakingTypeIcon: Landmark,
  },
  {
    id: "aave-safety-module",
    name: "Aave Safety Module",
    protocol: "Aave",
    token: "Aave",
    tokenSymbol: "AAVE",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 7.3,
    tvl: 120000000,
    lockPeriod: 10,
    lockPeriodText: "10 days cooldown",
    minStake: 0.1,
    rewards: ["stkAAVE"],
    rewardTokens: ["stkAAVE"],
    rewardLogos: ["/placeholder.svg?height=32&width=32"],
    riskLevel: "Medium",
    isLiquidStaking: false,
    isVerified: true,
    chain: "Ethereum",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: false,
    description: "Stake AAVE tokens in the Safety Module to secure the protocol and earn rewards.",
    stakingType: "Governance",
    stakingTypeLabel: "Governance Staking",
    stakingTypeIcon: Layers,
  },
  {
    id: "cosmos-atom",
    name: "Cosmos Staking",
    protocol: "Cosmos",
    token: "Cosmos",
    tokenSymbol: "ATOM",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 19.5,
    tvl: 980000000,
    lockPeriod: 21,
    lockPeriodText: "21 days unbonding",
    minStake: 0.1,
    rewards: ["Staking Rewards"],
    rewardTokens: ["ATOM"],
    rewardLogos: ["/placeholder.svg?height=32&width=32"],
    riskLevel: "Medium",
    isLiquidStaking: false,
    isVerified: true,
    chain: "Cosmos",
    chainLogo: "/placeholder.svg?height=16&width=16",
    isFavorite: false,
    description: "Stake ATOM with validators to secure the Cosmos Hub and earn staking rewards.",
    stakingType: "PoS",
    stakingTypeLabel: "Proof of Stake",
    stakingTypeIcon: Landmark,
  },
]

export const activeStakes: ActiveStake[] = [
  {
    id: "stake-1",
    poolId: "eth-consensus",
    poolName: "Ethereum Consensus Layer",
    protocol: "Ethereum",
    token: "Ethereum",
    tokenSymbol: "ETH",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    stakedAmount: 32,
    stakedValue: 96000,
    rewards: 0.42,
    rewardsValue: 1260,
    rewardToken: "ETH",
    rewardTokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 4.2,
    startDate: "2023-06-15",
    endDate: null,
    isLocked: false,
    remainingLockTime: null,
    chain: "Ethereum",
    chainLogo: "/placeholder.svg?height=16&width=16",
  },
  {
    id: "stake-2",
    poolId: "binance-bnb",
    poolName: "BNB Staking",
    protocol: "Binance",
    token: "BNB",
    tokenSymbol: "BNB",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    stakedAmount: 50,
    stakedValue: 15000,
    rewards: 0.89,
    rewardsValue: 267,
    rewardToken: "BNB",
    rewardTokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 6.5,
    startDate: "2023-09-01",
    endDate: "2023-10-01",
    isLocked: true,
    remainingLockTime: 12,
    chain: "BNB Chain",
    chainLogo: "/placeholder.svg?height=16&width=16",
  },
  {
    id: "stake-3",
    poolId: "solana-staking",
    poolName: "Solana Staking",
    protocol: "Solana",
    token: "Solana",
    tokenSymbol: "SOL",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    stakedAmount: 200,
    stakedValue: 20000,
    rewards: 4.2,
    rewardsValue: 420,
    rewardToken: "SOL",
    rewardTokenLogo: "/placeholder.svg?height=32&width=32",
    apy: 7.8,
    startDate: "2023-08-10",
    endDate: null,
    isLocked: false,
    remainingLockTime: null,
    chain: "Solana",
    chainLogo: "/placeholder.svg?height=16&width=16",
  },
]

export const historicalApyData: HistoricalData[] = [
  { date: "Jan", apy: 4.1 },
  { date: "Feb", apy: 4.3 },
  { date: "Mar", apy: 4.2 },
  { date: "Apr", apy: 4.0 },
  { date: "May", apy: 3.9 },
  { date: "Jun", apy: 4.1 },
  { date: "Jul", apy: 4.2 },
  { date: "Aug", apy: 4.3 },
  { date: "Sep", apy: 4.5 },
  { date: "Oct", apy: 4.4 },
  { date: "Nov", apy: 4.3 },
  { date: "Dec", apy: 4.2 },
]

export const portfolioAllocation: PortfolioAllocation[] = [
  { name: "ETH", value: 96000, color: "#627EEA" },
  { name: "BNB", value: 15000, color: "#F3BA2F" },
  { name: "SOL", value: 20000, color: "#00FFA3" },
]
