import type { YieldFarmingOpportunity, UserFarm } from "./types"

export const mockOpportunities: YieldFarmingOpportunity[] = [
  {
    id: 1,
    protocol: "Uniswap",
    asset: "ETH-USDC",
    chain: "Ethereum",
    farmType: "Liquidity Pool",
    apy: 45.2,
    tvl: 125000000,
    risk: "Low",
    impermanentLossRisk: "Medium",
    rewards: ["UNI", "Trading Fees"],
    logo: "/placeholder.svg",
  },
  {
    id: 2,
    protocol: "Aave",
    asset: "USDT",
    chain: "Polygon",
    farmType: "Lending",
    apy: 12.8,
    tvl: 450000000,
    risk: "Low",
    rewards: ["AAVE", "MATIC"],
    logo: "/placeholder.svg",
  },
  {
    id: 3,
    protocol: "PancakeSwap",
    asset: "BNB-BUSD",
    chain: "BSC",
    farmType: "Liquidity Pool",
    apy: 68.5,
    tvl: 85000000,
    risk: "Medium",
    impermanentLossRisk: "High",
    rewards: ["CAKE"],
    logo: "/placeholder.svg",
  },
  {
    id: 4,
    protocol: "Compound",
    asset: "DAI",
    chain: "Ethereum",
    farmType: "Lending",
    apy: 8.3,
    tvl: 320000000,
    risk: "Low",
    rewards: ["COMP"],
    logo: "/placeholder.svg",
  },
  {
    id: 5,
    protocol: "Curve",
    asset: "3Pool",
    chain: "Ethereum",
    farmType: "Staking",
    apy: 15.7,
    tvl: 890000000,
    risk: "Low",
    impermanentLossRisk: "Low",
    rewards: ["CRV", "CVX"],
    lockPeriod: "7 days",
    logo: "/placeholder.svg",
  },
]

export const mockUserFarms: UserFarm[] = [
  {
    id: 1,
    protocol: "Uniswap",
    asset: "ETH-USDC",
    apy: 45.2,
    deposited: 5000,
    earned: 125.5,
    logo: "/placeholder.svg",
  },
  {
    id: 2,
    protocol: "Aave",
    asset: "USDT",
    apy: 12.8,
    deposited: 10000,
    earned: 85.2,
    logo: "/placeholder.svg",
  },
]
